version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/resume_db
      - UPLOAD_FOLDER=/app/uploads
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resume_db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
